<?php 
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Index view script
 * 
 * @package    Application
 */

$this->headTitle('Listings - Kapitel 20');
$this->pageTitle('Listings - Kapitel 20');
?>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing2001">Listing 20.1</a></td>
<td>Modul-Konfiguration in <code>module.config.php</code></td>
</tr>
<tr>
<td><a href="/listing/listing2002">Listing 20.2</a></td>
<td>Lokale Konfigurationsdatei <code>/config/autoload/local.php</code></td>
</tr>
<tr>
<td><a href="/listing/listing2003">Listing 20.3</a></td>
<td>Laden der ClassMap in der <code>Module.php</code> konfigurieren</td>
</tr>
<tr>
<td><a href="/listing/listing2004">Listing 20.4</a></td>
<td><code>B8Service</code> für Zugriff auf <code>b8</code>-Objekt</td>
</tr>
<tr>
<td><a href="/listing/listing2005">Listing 20.5</a></td>
<td>Factory-Klasse für den <code>B8Service</code></td>
</tr>
<tr>
<td><a href="/listing/listing2006">Listing 20.6</a></td>
<td><code>SpamCheck</code> Controller-Plugin ermöglicht Zugriff auf <code>B8Service</code></td>
</tr>
<tr>
<td><a href="/listing/listing2007">Listing 20.7</a></td>
<td><code>SpamCheck</code> View-Helper ermöglicht Zugriff auf <code>B8Service</code></td>
</tr>
<tr>
<td><a href="/listing/listing208">Listing 20.8</a></td>
<td>Geänderte Konfiguration für <code>Comment</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing209">Listing 20.9</a></td>
<td>Geänderte Klasse <code>CommentEntity</code> für das <code>Comment</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing2010">Listing 20.10</a></td>
<td>Geänderter <code>CommentService</code> für Zugriff auf <code>B8Service</code></td>
</tr>
<tr>
<td><a href="/listing/listing2011">Listing 20.11</a></td>
<td><code>LoadComment</code> Controller-Plugin zum Laden von Kommentaren</td>
</tr>
<tr>
<td><a href="/listing/listing2012">Listing 20.12</a></td>
<td>Geänderter <code>AdminController</code> für <code>Comment</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing2013">Listing 20.13</a></td>
<td>Geänderte <code>index.phtml</code> für Anzeige der Spam Klassifizierung</td>
</tr>
<tr>
<td><a href="/listing/listing2014">Listing 20.14</a></td>
<td>Geänderte <code>show.phtml</code> für Anzeige der neuen Buttons</td>
</tr>
</tbody>
</table>
