<?php 
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 20.11 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 20.11');
$this->pageTitle('Listing 20.11');
?>
<h3><code>LoadComment</code> Controller-Plugin zum Laden von Kommentaren</h3>
<pre>
&lt;?php
namespace Comment\Controller\Plugin;

use Zend\Mvc\Controller\Plugin\AbstractPlugin;
use Comment\Entity\CommentEntityInterface;
use Comment\Service\CommentServiceInterface;

class LoadComment extends AbstractPlugin
{
    protected $commentService;

    public function __construct(CommentServiceInterface $commentService)
    {
        $this->setCommentService($commentService);
    }

    public function setCommentService(CommentServiceInterface $commentService = null)
    {
        $this->commentService = $commentService;
        return $this;
    }
    
    public function getCommentService()
    {
        return $this->commentService;
    }
    
    public function __invoke()
    {
        $controller = $this->getController();
        
        $id = (int) $controller->params()->fromRoute('id', 0);
        if (!$id) {
            $controller->redirect()->toRoute('comment-admin');
            return false;
        }
        
        $comment = $this->getCommentService()->fetchSingleById($id);
        
        if ($comment === false) {
            $controller->redirect()->toRoute('comment-admin');
            return false;
        }
        
        return $comment;
    }
}
</pre>
