<?php 
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 20.10 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 20.10');
$this->pageTitle('Listing 20.10');
?>
<h3>Geänderter <code>CommentService</code> für Zugriff auf <code>B8Service</code></h3>
<pre>
&lt;?php
namespace Comment\Service;

[...]
use SpamCheck\Service\B8ServiceInterface;

class CommentService implements EventManagerAwareInterface, CommentServiceInterface
{
    [...]
    
    protected $b8Service;

    public function __construct(
        CommentTableInterface $table, array $config, B8ServiceInterface $b8Service
    )
    {
        $this->setTable($table);
        $this->setConfig($config);
        $this->setB8Service($b8Service);
    }
    
    [...]

    public function setB8Service(B8ServiceInterface $b8Service = null)
    {
        $this->b8Service = $b8Service;
        return $this;
    }
    
    public function getB8Service()
    {
        return $this->b8Service;
    }
    
    [...]
    
    public function save(array $data, $id = null)
    {
        [...]
        
        // check spam detect
        if ($this->getConfig('spamDetect')) {
            if ($this->getB8Service()->detectSpam($comment->getFullText())) {
                $newStatus = $this->getConfig('spamStatus');
            } else {
                $newStatus = $this->getConfig('hamStatus');
            }
        } else {
            $newStatus = $this->getConfig('newStatus');
        }
        
        [...]
    }
    
    [...]
}
</pre>
