<?php 
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 20.7 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 20.7');
$this->pageTitle('Listing 20.7');
?>
<h3><code>SpamCheck</code> View-Helper ermöglicht Zugriff auf <code>B8Service</code></h3>
<pre>
&lt;?php
namespace SpamCheck\View\Helper;

use SpamCheck\Service\B8ServiceInterface;
use Zend\View\Helper\AbstractHelper;
use Zend\View\Model\ViewModel;

class SpamCheck extends AbstractHelper
{
    protected $b8Service;

    public function __construct(B8ServiceInterface $b8Service)
    {
        $this->setB8Service($b8Service);
    }

    public function setB8Service(B8ServiceInterface $b8Service = null)
    {
        $this->b8Service = $b8Service;
        return $this;
    }
    
    public function getB8Service()
    {
        return $this->b8Service;
    }
    
    public function __invoke()
    {
        return $this;
    }
    
    public function classify($text, $round = 10)
    {
        $round = $round == 0 ? 10 : (integer) $round;
        return round($this->getB8Service()->classify($text), $round);
    }
}
</pre>
