<?php 
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 20.2 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 20.2');
$this->pageTitle('Listing 20.2');
?>
<h3>Lokale Konfigurationsdatei <code>/config/autoload/local.php</code></h3>
<pre>
&lt;?php
return array(
    [...]
    'b8' => array(
        'config_database' => array(
            'database'   => 'luigis-pizza',
            'host'       => 'localhost',
            'user'       => 'luigis-pizza',
            'pass'       => 'luigis-pizza',
        ),
    ),
);
</pre>
