<?php 
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 20.12 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 20.12');
$this->pageTitle('Listing 20.12');
?>
<h3>Geänderter <code>AdminController</code> für <code>Comment</code> Modul</h3>
<pre>
&lt;?php
namespace Comment\Controller;

namespace Comment\Controller;

use Zend\Http\PhpEnvironment\Response;
use Zend\View\Model\ViewModel;
use Zend\Mvc\Controller\AbstractActionController;
use Comment\Service\CommentServiceInterface;

class AdminController extends AbstractActionController
{
    protected $commentService;
    
    public function setCommentService(CommentServiceInterface $commentService)
    {
        $this->commentService = $commentService;
    
        return $this;
    }
    
    public function getCommentService()
    {
        return $this->commentService;
    }
    
    public function indexAction()
    {
        // read page from route
        $page = (int) $this->params()->fromRoute('page');
        
        // set max comment per page
        $maxPage = 10;
        
        // read data and pass to view
        return new ViewModel(array(
            'commentList' => $this->getCommentService()->fetchList($page, $maxPage),
        ));
    }
    
    public function showAction()
    {
        // load comment
        if (!$comment = $this->loadComment()) {
            return $this->getResponse();
        }
        
        // pass comment to view
        return new ViewModel(array(
            'comment' => $comment,
        ));
    }
    
    public function updateAction()
    {
        // load comment
        if (!$comment = $this->loadComment()) {
            return $this->getResponse();
        }
        
        // prepare Post/Redirect/Get Plugin
        $prg = $this->prg(
            $this->url()->fromRoute('comment-admin/action', array(), array(), true), 
            true
        );
        
        // check PRG plugin for redirect to send
        if ($prg instanceof Response) {
            return $prg;
            
        // check PRG for redirect to process
        } elseif ($prg !== false) {
            // check for cancel
            if (isset($prg['cancel'])) {
                // Redirect to list of comments
                return $this->redirect()->toRoute('comment-admin');
            }
            
            // update with redirected data
            $comment = $this->getCommentService()->save($prg, $comment->getId());
            
            // check comment
            if ($comment) {
                // add messages to flash messenger
                $this->flashMessenger()->addMessage(
                    $this->getCommentService()->getMessage()
                );
                
                // Redirect to update comment
                return $this->redirect()->toRoute(
                    'comment-admin/action', array(), array(), true
                );
            }
        }
        
        // get form and bind object
        $form = $this->getCommentService()->getForm('update');
        
        //check prg
        if ($prg === false) {
            $form->bind($comment);
        }
        
        // add messages to flash messenger
        if ($this->getCommentService()->getMessage()) {
            $this->flashMessenger()->addMessage(
                $this->getCommentService()->getMessage()
            );
        }
        
        // no post or update unsuccesful
        return new ViewModel(array(
            'form' => $form,
            'comment' => $comment,
        ));
    }
    
    public function deleteAction()
    {
        // load comment
        if (!$comment = $this->loadComment()) {
            return $this->getResponse();
        }
        
        // prepare Post/Redirect/Get Plugin
        $prg = $this->prg(
            $this->url()->fromRoute('comment-admin/action', array(), array(), true), 
            true
        );
        
        // check PRG plugin for redirect to send
        if ($prg instanceof Response) {
            return $prg;
            
        // check PRG for redirect to process
        } elseif ($prg !== false) {
            // check for cancel
            if (isset($prg['cancel'])) {
                // Redirect to list of comments
                return $this->redirect()->toRoute('comment-admin');
            }
            
            // delete with redirected data
            $comment = $this->getCommentService()->delete($comment->getId());
            
            // check comment
            if ($comment) {
                // add messages to flash messenger
                $this->flashMessenger()->addMessage(
                    $this->getCommentService()->getMessage()
                );
                
                // Redirect to list of comment
                return $this->redirect()->toRoute('comment-admin');
            }
        }
        
        // get form and bind object
        $form = $this->getCommentService()->getForm('delete');
        
        //check prg
        if ($prg === false) {
            $form->bind($comment);
        }
        
        // add messages to flash messenger
        if ($this->getCommentService()->getMessage()) {
            $this->flashMessenger()->addMessage(
                $this->getCommentService()->getMessage()
            );
        }
        
        // no post or update unsuccesful
        return new ViewModel(array(
            'form' => $form,
            'comment' => $comment,
        ));
    }
    
    public function spamAction()
    {
        // load comment
        if (!$comment = $this->loadComment()) {
            return $this->getResponse();
        }
        
        // mark as spam
        $this->spamCheck()->markAsSpam($comment->getFullText());
        
        // change status
        $this->getCommentService()->updateStatus($comment->getId(), 'blocked');
        
        // redirect
        return $this->redirect()->toRoute('comment-admin/action', array(
            'action' => 'show', 'id' => $comment->getId())
        );
    }
    
    public function hamAction()
    {
        // load comment
        if (!$comment = $this->loadComment()) {
            return $this->getResponse();
        }
        
        // mark as ham
        $this->spamCheck()->markAsHam($comment->getFullText());
        
        // change status
        $this->getCommentService()->updateStatus($comment->getId(), 'approved');
        
        // redirect
        return $this->redirect()->toRoute('comment-admin/action', array(
            'action' => 'show', 'id' => $comment->getId())
        );
    }
    
    public function noSpamAction()
    {
        // load comment
        if (!$comment = $this->loadComment()) {
            return $this->getResponse();
        }
        
        // mark as no spam
        $this->spamCheck()->markAsNoSpam($comment->getFullText());
    
        // change status
        $this->getCommentService()->updateStatus($comment->getId(), 'new');
    
        // redirect
        return $this->redirect()->toRoute('comment-admin/action', array(
            'action' => 'show', 'id' => $comment->getId())
        );
    }
    
    public function noHamAction()
    {
        // load comment
        if (!$comment = $this->loadComment()) {
            return $this->getResponse();
        }
        
        // mark as no ham
        $this->spamCheck()->markAsNoHam($comment->getFullText());
    
        // change status
        $this->getCommentService()->updateStatus($comment->getId(), 'new');
    
        // redirect
        return $this->redirect()->toRoute('comment-admin/action', array(
            'action' => 'show', 'id' => $comment->getId())
        );
    }
}
</pre>
