<?php 
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch 'Zend Framework 2 - Das Praxisbuch'
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 20.3 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 20.3');
$this->pageTitle('Listing 20.3');
?>
<h3>Laden der ClassMap in der <code>Module.php</code> konfigurieren</h3>
<pre>
&lt;?php
namespace SpamCheck;

[...]

class Module implements 
    ConfigProviderInterface, 
    AutoloaderProviderInterface
{
    [...]
    
    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\ClassMapAutoloader' => array(
                'spamCheck' => __DIR__ . '/autoload_classmap.php',
            ),
            [...]
        );
    }
}
</pre>
