<?php 
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 20.5 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 20.5');
$this->pageTitle('Listing 20.5');
?>
<h3>Factory-Klasse für den <code>B8Service</code></h3>
<pre>
&lt;?php
namespace SpamCheck\Service;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class B8ServiceFactory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $config  = $serviceLocator->get('Config');
        $b8      = new \b8(
            $config['b8']['config_b8'], $config['b8']['config_database']
        );
        $service = new B8Service($b8);
        return $service;
    }
}
</pre>
