<?php
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Sidebar view script
 * 
 * @package    Application
 */

$url = $this->url(
    'application', array('controller' => 'about', 'action' => 'team')
);

if ($this->getHelperPluginManager()->has('userShowWidget')) {
    echo $this->userShowWidget();
}
?>
<div class="well">
<h4 class="pull-center">Ihr Team</h4>
<div class="pull-center">
<a href="<?php echo $url?>"><img src="/img/team/team.png" alt="Team" /></a>
<p><small>Luigi, Francesca, Alessandro, Valentina</small></p>
</div>
</div>
