<?php 
/**
 * ZF2 Buch Kapitel 20
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Comment
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * namespace definition and usage
 */
use Comment\Entity\CommentEntity;

/**
 * Comment-Admin show view script
 * 
 * @package    Comment
 */

$this->headTitle('Kommentar anzeigen');
$this->pageTitle('Einen Kommentar anzeigen');

// set comment entity
$comment = $this->comment; /* @var $comment CommentEntity */

// set show url
$urlComment = $comment->getUrl();
$urlCancel  = $this->url('comment-admin');
$urlEdit    = $this->url(
    'comment-admin/action', array('action' => 'update', 'id' => $comment->getId())
);
$urlDelete  = $this->url(
    'comment-admin/action', array('action' => 'delete', 'id' => $comment->getId())
);
?>
<table class="table table-data">
<tbody>
<tr>
<th>Datum</th>
<td><?php echo $this->date($comment->getCdate()); ?></td>
</tr>
<tr>
<th>Url</th>
<td><a href="<?php echo $urlComment; ?>"><?php echo $urlComment; ?></a></td>
</tr>
<tr>
<th>Status</th>
<td><?php echo $comment->getStatusName(); ?></td>
</tr>
<tr>
<th>E-Mail-Adresse</th>
<td><?php echo $comment->getEmail(); ?></td>
</tr>
<tr>
<th>Name</th>
<td><?php echo $comment->getName(); ?></td>
</tr>
<tr>
<th>Kommentar</th>
<td><?php echo $comment->getMessage(); ?></td>
</tr>
</tbody>
</table>
<div class="form-horizontal">
<div class="form-actions">
<a href="<?php echo $urlEdit; ?>" class="btn"><i class="icon-pencil"></i> Bearbeiten</a>
<a href="<?php echo $urlDelete; ?>" class="btn"><i class="icon-trash"></i> Löschen</a>
<a href="<?php echo $urlCancel; ?>" class="btn"><i class="icon-ban-circle"></i> Abbrechen</a>
</div>
</div>
